apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-br-default-channel
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
data:
  channel-template-spec: {{ .Values.configBrDefaultChannel.channelTemplateSpec |
    toYaml | indent 1 }}