apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-leader-election
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: f7948630
data:
  _example: {{ .Values.configLeaderElection.Example | toYaml | indent 1 }}