apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-kreference-mapping
  labels:
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 7375dbe1
data:
  _example: {{ .Values.configKreferenceMapping.Example | toYaml | indent 1 }}