apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-features
  labels:
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
data:
  delivery-retryafter: {{ .Values.configFeatures.deliveryRetryafter | quote }}
  delivery-timeout: {{ .Values.configFeatures.deliveryTimeout | quote }}
  eventtype-auto-create: {{ .Values.configFeatures.eventtypeAutoCreate | quote }}
  kreference-group: {{ .Values.configFeatures.kreferenceGroup | quote }}
  kreference-mapping: {{ .Values.configFeatures.kreferenceMapping | quote }}
  new-trigger-filters: {{ .Values.configFeatures.newTriggerFilters | quote }}
  transport-encryption: {{ .Values.configFeatures.transportEncryption | quote }}