apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-tracing
  labels:
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 0492ceb0
data:
  _example: {{ .Values.configTracing.Example | toYaml | indent 1 }}