apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-observability
  labels:
    knative.dev/config-category: eventing
    knative.dev/config-propagation: original
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: f46cf09d
data:
  _example: {{ .Values.configObservability.Example | toYaml | indent 1 }}