apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-config-ping-defaults
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/version: 1.11.5
    knative.dev/example-checksum: 9185c153
data:
  _example: {{ .Values.configPingDefaults.Example | toYaml | indent 1 }}