apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-default-ch-webhook
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
data:
  default-ch-config: {{ .Values.defaultChWebhook.defaultChConfig | toYaml | indent
    1 }}