apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-sources-source-observer
  labels:
    duck.knative.dev/source: "true"
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - sources.knative.dev
  resources:
  - apiserversources
  - pingsources
  - sinkbindings
  - containersources
  verbs:
  - get
  - list
  - watch