apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: eventing-webhook
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eventing-webhook
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: eventing-webhook
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: eventing-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-webhook
  labels:
    app.kubernetes.io/component: eventing-webhook
    role: eventing-webhook
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.eventingWebhook.type }}
  selector:
    role: eventing-webhook
  {{- include "knative-eventing-core.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.eventingWebhook.ports | toYaml | nindent 2 -}}