apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-controller-sources-controller
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "knative-eventing-core.fullname" . }}-knative-eventing-sources-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "knative-eventing-core.fullname" . }}-eventing-controller'
  namespace: '{{ .Release.Namespace }}'