apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-knative-messaging-namespaced-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - messaging.knative.dev
  resources:
  - '*'
  verbs:
  - '*'