apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-meta-channelable-manipulator
  labels:
    duck.knative.dev/channelable: "true"
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - messaging.knative.dev
  resources:
  - channels
  - channels/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete