apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-serving-addressable-resolver
  labels:
    duck.knative.dev/addressable: "true"
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - routes
  - routes/status
  - services
  - services/status
  verbs:
  - get
  - list
  - watch