apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-service-addressable-resolver
  labels:
    duck.knative.dev/addressable: "true"
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch