apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-controller
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventingController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-pingsource-mt-adapter
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pingsourceMtAdapter.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-eventing-webhook
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventingWebhook.serviceAccount.annotations | nindent 4 }}