apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "knative-eventing-core.fullname" . }}-validation.webhook.eventing.knative.dev
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "knative-eventing-core.fullname" . }}-
  labels:
  {{- include "knative-eventing-core.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "knative-eventing-core.fullname" . }}-eventing-webhook'
      namespace: '{{ .Release.Namespace }}'
  failurePolicy: Fail
  name: validation.webhook.eventing.knative.dev
  sideEffects: None
  timeoutSeconds: 10