apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-activator-pdb
  labels:
    app.kubernetes.io/component: activator
  {{- include "knative-serving-core.labels" . | nindent 4 }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: activator