apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-config-network
  labels:
    app.kubernetes.io/component: networking
  {{- include "knative-serving-core.labels" . | nindent 4 }}
  annotations:
    knative.dev/example-checksum: 2b6d10ba
data:
  _example: {{ .Values.configNetwork.Example | toYaml | indent 1 }}