apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-knative-serving-certs
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    serving-certs-ctrl: data-plane
  {{- include "knative-serving-core.labels" . | nindent 4 }}