apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knative-serving-core.fullname" . }}-routing-serving-certs
  labels:
    networking.internal.knative.dev/certificate-uid: serving-certs
    routing-id: "0"
    serving-certs-ctrl: data-plane-routing
  {{- include "knative-serving-core.labels" . | nindent 4 }}